// ── Shared Data ──
// Generated by scripts/build-site.js into site-data.js.
const siteData = window.siteData || {};
const standingsData = siteData.standings || {};
const driverStandings = standingsData.drivers || [];
const constructorStandings = standingsData.constructors || [];
const standingsLastUpdated = standingsData.lastUpdated || '';
const driverWikipediaLinks = Object.fromEntries((siteData.drivers || []).map(function(driver) {
  return [driver.code, driver.links && driver.links.wikipedia];
}).filter(function(entry) { return entry[0] && entry[1]; }));
const constructorWikipediaLinks = Object.fromEntries((siteData.teams || []).map(function(team) {
  return [team.name, team.links && team.links.wikipedia];
}).filter(function(entry) { return entry[0] && entry[1]; }));
const championsConfig = siteData.champions || {};
const championsData = championsConfig.champions || [];
const championFlagMap = championsConfig.flagMap || {};
const championTeamColors = championsConfig.teamColors || {};
const constructorDrivers = championsConfig.constructorDrivers || {};

// ── World Champions Rendering ──
function renderChampionsTable(decade) {
  var container = document.getElementById('championsTable');
  if (!container) return;

  var startYear = parseInt(decade, 10);
  var endYear = startYear + 9;
  var rows = championsData.filter(function(d) { return d.year >= startYear && d.year <= endYear; });

  function getTeamColor(teamName) {
    if (!teamName) return '';
    return championTeamColors[teamName] || '';
  }

  var html = '<table class="champions-table">';
  html += '<thead><tr><th>Year</th><th>Driver</th><th>Constructor</th></tr></thead>';
  html += '<tbody>';

  rows.forEach(function(row) {
    var flag = championFlagMap[row.nationality] || '';
    var teamColor = getTeamColor(row.team);
    var constructorColor = getTeamColor(row.constructor);
    var styleProps = [];
    if (teamColor) styleProps.push('--row-team-color: ' + teamColor);
    if (constructorColor) styleProps.push('--row-constructor-color: ' + constructorColor);
    var style = styleProps.length ? ' style="' + styleProps.join('; ') + '"' : '';
    var teamColorAttr = teamColor ? ' data-team-color' : '';
    var constructorColorAttr = constructorColor ? ' data-constructor-color' : '';

    html += '<tr' + style + teamColorAttr + constructorColorAttr + '>';
    html += '<td class="champions-year">' + row.year + '</td>';
    html += '<td class="champions-driver"><span class="champions-flag">' + flag + '</span>' + row.driver + '<span class="champions-driver-team">';
    if (teamColor) html += '<span class="champions-team-color" style="background:' + teamColor + '"></span>';
    html += row.team + '</span></td>';

    if (row.constructor) {
      var drivers = constructorDrivers[row.year];
      html += '<td class="champions-constructor">';
      if (constructorColor) html += '<span class="champions-team-color" style="background:' + constructorColor + '"></span>';
      html += row.constructor;
      if (drivers) html += '<span class="champions-constructor-drivers">' + drivers[0] + ' &middot; ' + drivers[1] + '</span>';
      html += '</td>';
    } else {
      html += '<td class="champions-na">&mdash;</td>';
    }

    html += '</tr>';
  });

  html += '</tbody></table>';
  container.innerHTML = html;
}

(function initChampionsTabs() {
  var tabs = document.querySelectorAll('.champions-tab');
  if (!tabs.length) return;

  function activateTab(tab) {
    tabs.forEach(function(t) {
      t.classList.remove('active');
      t.setAttribute('aria-selected', 'false');
      t.setAttribute('tabindex', '-1');
    });
    tab.classList.add('active');
    tab.setAttribute('aria-selected', 'true');
    tab.setAttribute('tabindex', '0');
    tab.focus();

    // Fade transition: fade out, swap content, fade in
    var wrapper = document.getElementById('championsTable');
    if (wrapper && !window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
      wrapper.classList.add('is-switching');
      setTimeout(function() {
        renderChampionsTable(tab.dataset.decade);
        wrapper.classList.remove('is-switching');
      }, 150);
    } else {
      renderChampionsTable(tab.dataset.decade);
    }
  }

  tabs.forEach(function(tab) {
    tab.addEventListener('click', function() {
      activateTab(tab);
    });
  });

  // Keyboard navigation: left/right arrows
  var tabContainer = document.querySelector('.champions-tabs');
  if (tabContainer) {
    tabContainer.addEventListener('keydown', function(e) {
      var tabArray = Array.from(tabs);
      var currentIndex = tabArray.findIndex(function(t) { return t.classList.contains('active'); });
      if (e.key === 'ArrowRight' || e.key === 'ArrowLeft') {
        e.preventDefault();
        var newIndex;
        if (e.key === 'ArrowRight') {
          newIndex = (currentIndex + 1) % tabArray.length;
        } else {
          newIndex = (currentIndex - 1 + tabArray.length) % tabArray.length;
        }
        activateTab(tabArray[newIndex]);
      }
    });
  }

  // Render default tab (2020s)
  renderChampionsTable('2020');
})();

// ── Theme Toggle ──
function toggleTheme() {
  const html = document.documentElement;
  const current = html.getAttribute('data-theme');
  const next = current === 'dark' ? 'light' : 'dark';
  html.setAttribute('data-theme', next);
  localStorage.setItem('f1-guide-theme', next);
}

// Restore saved theme
(function() {
  const saved = localStorage.getItem('f1-guide-theme');
  if (saved) document.documentElement.setAttribute('data-theme', saved);
})();

// ── Unit Toggle ──
function setUnits(unit) {
  document.documentElement.setAttribute('data-units', unit);
  document.querySelectorAll('.unit').forEach(el => {
    el.textContent = el.dataset[unit];
  });
  document.querySelectorAll('.unit-toggle__btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.unit === unit);
  });
  localStorage.setItem('f1-units', unit);
}

// Restore saved units
(function() {
  const saved = localStorage.getItem('f1-units');
  if (saved) setUnits(saved);
})();

// ── Navbar scroll effect ──
const navbar = document.getElementById('navbar');
window.addEventListener('scroll', () => {
  navbar.classList.toggle('scrolled', window.scrollY > 80);
});

// ── Scroll reveal ──
const revealElements = document.querySelectorAll('.reveal');
const revealObserver = new IntersectionObserver((entries) => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      entry.target.classList.add('visible');
      revealObserver.unobserve(entry.target);
    }
  });
}, { threshold: 0.1, rootMargin: '0px 0px -40px 0px' });

revealElements.forEach(el => revealObserver.observe(el));

// ── Hero lights animation ──
(function animateLights() {
  const lights = document.querySelectorAll('.hero__light');
  let i = 0;

  function lightUp() {
    if (i < lights.length) {
      lights[i].classList.add('on');
      i++;
      setTimeout(lightUp, 600);
    } else {
      setTimeout(() => {
        lights.forEach(l => l.classList.remove('on'));
        i = 0;
        setTimeout(lightUp, 2000);
      }, 1500);
    }
  }

  setTimeout(lightUp, 800);
})();

// ── Pit stop timer animation ──
const pitstopTimer = document.getElementById('pitstopTimer');
const pitstopObserver = new IntersectionObserver((entries) => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      animatePitstop();
      pitstopObserver.unobserve(entry.target);
    }
  });
}, { threshold: 0.5 });

pitstopObserver.observe(pitstopTimer);

function animatePitstop() {
  const target = 1.80;
  const duration = 1800;
  const start = performance.now();

  function update(now) {
    const elapsed = now - start;
    const progress = Math.min(elapsed / duration, 1);
    const eased = 1 - Math.pow(1 - progress, 3);
    const current = (eased * target).toFixed(2);
    pitstopTimer.textContent = current;

    if (progress < 1) {
      requestAnimationFrame(update);
    } else {
      pitstopTimer.textContent = '1.80';
    }
  }

  requestAnimationFrame(update);
}

// ── Engine audio player ──
const engineRows = Array.from(document.querySelectorAll('.pu-supplier--interactive'));
const engineAudioPlayer = document.getElementById('engineAudioPlayer');
let activeEngineId = null;

// Haptic feedback for Honda engine sound
// iOS: uses a hidden <input type="checkbox" switch> clicked every rAF frame.
// Full 60fps clicking produces the smoothest sustained haptic buzz.
// The element is recreated every ~1s (60 frames) to reset any iOS
// throttling that causes the haptic to stop after a few seconds.
// Android: uses navigator.vibrate() with a long repeating pattern.
let hapticRunning = false;
let hapticLabel = null;
let hapticFrameCount = 0;

function createHapticEl() {
  if (hapticLabel) hapticLabel.remove();
  const label = document.createElement('label');
  label.ariaHidden = 'true';
  label.style.position = 'fixed';
  label.style.left = '-9999px';
  label.style.top = '-9999px';
  label.style.opacity = '0';
  label.style.pointerEvents = 'none';
  const input = document.createElement('input');
  input.type = 'checkbox';
  input.setAttribute('switch', '');
  label.appendChild(input);
  document.body.appendChild(label);
  hapticLabel = label;
  hapticFrameCount = 0;
}

function hapticLoop() {
  if (!hapticRunning) return;
  hapticFrameCount++;
  // Recreate element every ~1s to reset any iOS throttling
  if (hapticFrameCount >= 60) {
    createHapticEl();
  }
  if (hapticLabel) hapticLabel.click();
  requestAnimationFrame(hapticLoop);
}

function startHondaHaptic() {
  if (hapticRunning) return;
  hapticRunning = true;

  // Android: long repeating vibration pattern covering up to 60s
  if (typeof navigator.vibrate === 'function') {
    const unit = [80, 60, 50, 80, 40];
    const reps = Math.ceil(60000 / 310);
    const pattern = [];
    for (let i = 0; i < reps; i++) {
      pattern.push(...unit);
    }
    navigator.vibrate(pattern);
  }

  // iOS: click hidden switch checkbox every frame for smooth haptic
  createHapticEl();
  requestAnimationFrame(hapticLoop);
}

function stopHondaHaptic() {
  const wasRunning = hapticRunning || Boolean(hapticLabel);
  hapticRunning = false;
  if (hapticLabel) {
    hapticLabel.remove();
    hapticLabel = null;
  }
  if (wasRunning && typeof navigator.vibrate === 'function') navigator.vibrate(0);
}

function updateEngineRows() {
  const isPlaying = engineAudioPlayer ? !engineAudioPlayer.paused : false;
  const hondaIsPlaying = activeEngineId === 'honda' && isPlaying;

  if (hondaIsPlaying) {
    startHondaHaptic();
  } else {
    stopHondaHaptic();
  }

  engineRows.forEach((row) => {
    const rowEngineId = row.dataset.engineId;
    const rowEngineName = row.dataset.engineName;
    const rowIsActive = rowEngineId === activeEngineId;
    const rowIsPlaying = rowIsActive && isPlaying;
    const stateText = rowIsPlaying ? 'Playing' : rowIsActive ? 'Paused' : 'Play';
    const labelAction = rowIsPlaying ? 'Pause' : 'Play';
    const playState = row.querySelector('.pu-supplier__playstate');

    row.classList.toggle('is-active', rowIsActive);
    row.classList.toggle('is-playing', rowIsPlaying);
    row.setAttribute('aria-pressed', String(rowIsActive));
    row.setAttribute('aria-label', `${labelAction} ${rowEngineName} engine sound`);
    if (playState) playState.textContent = stateText;
  });
}

function toggleEnginePlayback(row) {
  if (!engineAudioPlayer) return;
  const engineId = row.dataset.engineId;
  const engineName = row.dataset.engineName;
  const audioSrc = row.dataset.audioSrc;

  if (!engineId || !engineName || !audioSrc) return;

  if (activeEngineId === engineId) {
    if (engineAudioPlayer.paused) {
      engineAudioPlayer.play().then(() => {
        updateEngineRows();
      }).catch(() => {
        console.warn(`Couldn't play ${engineName} right now.`);
        activeEngineId = null;
        updateEngineRows();
      });
    } else {
      engineAudioPlayer.pause();
    }
    updateEngineRows();
    return;
  }

  activeEngineId = engineId;
  engineAudioPlayer.src = audioSrc;
  engineAudioPlayer.currentTime = 0;
  engineAudioPlayer.play().then(() => {
    updateEngineRows();
  }).catch(() => {
    console.warn(`Couldn't load ${engineName}.`);
    activeEngineId = null;
    updateEngineRows();
  });
  updateEngineRows();
}

if (engineRows.length && engineAudioPlayer) {
  engineRows.forEach((row) => {
    row.addEventListener('click', () => toggleEnginePlayback(row));
  });

  engineAudioPlayer.addEventListener('play', updateEngineRows);
  engineAudioPlayer.addEventListener('pause', updateEngineRows);
  engineAudioPlayer.addEventListener('ended', () => {
    activeEngineId = null;
    updateEngineRows();
  });
  engineAudioPlayer.addEventListener('error', () => {
    const failedRow = engineRows.find((row) => row.dataset.engineId === activeEngineId);
    const failedName = failedRow ? failedRow.dataset.engineName : 'this clip';
    console.warn(`Audio unavailable for ${failedName}.`);
    activeEngineId = null;
    updateEngineRows();
  });

  updateEngineRows();
}

// ── Action bindings (replaces inline onclick handlers) ──
document.addEventListener('click', function(e) {
  const trigger = e.target.closest('[data-action]');
  if (!trigger) return;
  const action = trigger.dataset.action;

  if (action === 'set-units') {
    e.preventDefault();
    setUnits(trigger.dataset.unit || 'imperial');
  } else if (action === 'toggle-theme') {
    e.preventDefault();
    toggleTheme();
  } else if (action === 'toggle-mobile-nav') {
    e.preventDefault();
    toggleMobileNav();
  } else if (action === 'close-mobile-nav') {
    closeMobileNav();
  } else if (action === 'copy-url') {
    e.preventDefault();
    copyPageUrl();
  } else if (action === 'native-share') {
    e.preventDefault();
    nativeShare();
  }
});

// ── Smooth scroll for nav links ──
document.querySelectorAll('.navbar__links a, .mobile-nav__toc-link, .toc__link').forEach(link => {
  link.addEventListener('click', (e) => {
    e.preventDefault();
    const target = document.querySelector(link.getAttribute('href'));
    if (target) {
      target.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  });
});

// ── Mobile nav ──
function toggleMobileNav() {
  const nav = document.getElementById('mobileNav');
  const btn = document.getElementById('hamburgerBtn');
  nav.classList.toggle('open');
  btn.classList.toggle('active');
}

function closeMobileNav() {
  document.getElementById('mobileNav').classList.remove('open');
  document.getElementById('hamburgerBtn').classList.remove('active');
}

// Close mobile nav on resize to desktop
window.addEventListener('resize', () => {
  if (window.innerWidth > 1024) closeMobileNav();
});

// ── Active nav link on scroll ──
const navLinks = document.querySelectorAll('.navbar__links a');
const tocLinks = document.querySelectorAll('.toc__link');
const mobileTocLinks = document.querySelectorAll('.mobile-nav__toc-link');
const sectionObserver = new IntersectionObserver((entries) => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      const id = entry.target.getAttribute('id');
      navLinks.forEach(link => {
        link.classList.toggle('active', link.getAttribute('href') === '#' + id);
      });
      tocLinks.forEach(link => {
        link.classList.toggle('active', link.getAttribute('href') === '#' + id);
      });
      mobileTocLinks.forEach(link => {
        link.classList.toggle('active', link.getAttribute('href') === '#' + id);
      });
    }
  });
}, { threshold: 0, rootMargin: '-50% 0px -50% 0px' });

document.querySelectorAll('section[id]').forEach(section => {
  sectionObserver.observe(section);
});

// ── TOC visibility ──
(function() {
  const toc = document.getElementById('toc');
  const hero = document.querySelector('.hero');
  if (!toc || !hero) return;

  const tocObserver = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      toc.classList.toggle('visible', !entry.isIntersecting);
    });
  }, { threshold: 0 });

  tocObserver.observe(hero);
})();

// ── Share functionality ──
function announceShareResult(message) {
  const label = document.getElementById('copyUrlLabel');
  if (label) label.textContent = message;
  setTimeout(() => {
    if (label) label.textContent = 'Copy Link';
  }, 2000);
}

function copyPageUrl() {
  if (!navigator.clipboard || !navigator.clipboard.writeText) {
    announceShareResult('Clipboard blocked');
    return;
  }

  navigator.clipboard.writeText(window.location.href).then(() => {
    const btn = document.getElementById('copyUrlBtn');
    if (btn) btn.classList.add('copied');
    announceShareResult('Copied!');
    setTimeout(() => {
      if (btn) btn.classList.remove('copied');
    }, 2000);
  }).catch(() => {
    announceShareResult('Copy failed');
  });
}

function nativeShare() {
  if (!navigator.share) return;
  navigator.share({
    title: 'Welcome to Formula 1',
    text: 'Everything you need to know about Formula 1 — the cars, the drivers, the drama.',
    url: window.location.href
  }).catch(() => {
    announceShareResult('Use copy link');
  });
}

// Show native share button if supported
if (navigator.share) {
  document.getElementById('nativeShareBtn').style.display = 'flex';
}

// ── Race week banner + schedule rendering ──
(function() {
  const races = Array.isArray(window.racesData) ? window.racesData : [];
  const raceRows = races.filter(function(r) { return !r.type; });
  const scheduleGrid = document.getElementById('scheduleGrid');
  const timelineRaceSelect = document.getElementById('timelineRaceSelect');
  const timelinePanel = document.getElementById('timelinePanel');
  const timelineTimezoneCode = document.getElementById('timelineTimezoneCode');
  const calendarLastUpdated = document.getElementById('calendarLastUpdated');

  function formatRaceDetail(r) {
    const fp1 = new Date(r.fp1);
    const race = new Date(r.race);
    const start = fp1.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
    const end = race.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
    return r.location + ' \u2022 ' + start + '\u2013' + end;
  }

  function renderSchedule() {
    if (!scheduleGrid) return;
    scheduleGrid.innerHTML = '';

    races.forEach(function(item) {
      const card = document.createElement('div');
      card.className = 'schedule-item';

      if (item.type === 'break') {
        card.classList.add('schedule-item--break');
        card.innerHTML = '<span class="schedule-item__round">\u2014</span><div class="schedule-item__info"><span class="schedule-item__name">' + item.label + '</span><span class="schedule-item__detail">' + item.detail + '</span></div>';
        scheduleGrid.appendChild(card);
        return;
      }

      card.dataset.round = item.round;
      card.innerHTML = '<span class="schedule-item__round">R' + item.round + '</span><div class="schedule-item__info"><span class="schedule-item__name">' + item.name + (item.isNew ? ' <span class="schedule-item__badge">NEW</span>' : '') + '</span><span class="schedule-item__detail">' + formatRaceDetail(item) + '</span></div>';
      scheduleGrid.appendChild(card);
    });
  }

  function renderTimelineOptions() {
    if (!timelineRaceSelect) return;
    timelineRaceSelect.innerHTML = raceRows.map(function(r) {
      return '<option value="' + r.round + '">R' + r.round + ' \u00b7 ' + r.name + '</option>';
    }).join('');
  }

  function formatSessionLine(label, iso, note) {
    const d = new Date(iso);
    const when = d.toLocaleString([], { weekday: 'short', month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' });
    const noteHtml = note ? '<span class="timeline-row__note" title="' + note.title + '">' + note.text + '</span>' : '';
    return '<div class="timeline-row"><span>' + label + noteHtml + '</span><strong>' + when + '</strong></div>';
  }

  function getUserTimeZoneCode() {
    try {
      const userTimeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
      const januaryDate = new Date(Date.UTC(new Date().getUTCFullYear(), 0, 1));
      const formatter = new Intl.DateTimeFormat('en-US', { timeZone: userTimeZone, timeZoneName: 'short' });
      const tzPart = formatter.formatToParts(januaryDate).find(function(part) { return part.type === 'timeZoneName'; });
      return tzPart && tzPart.value ? tzPart.value : 'local time';
    } catch (error) {
      return 'local time';
    }
  }

  function renderTimeline(round) {
    if (!timelinePanel) return;
    const race = raceRows.find(function(r) { return String(r.round) === String(round); }) || raceRows[0];
    if (!race) return;
    const isSprint = Boolean(race.sprintWeekend);
    const sprintTag = isSprint ? '<span class="timeline-badge">Sprint weekend</span>' : '';
    const raceNote = race.raceNote || null;
    const noteSessionKey = raceNote && (raceNote.session || 'race');
    const noteFor = function(key) { return key === noteSessionKey ? raceNote : null; };
    const sessions = isSprint
      ? [
        ['FP1', race.fp1, noteFor('fp1')],
        ['Sprint Qualifying', race.sprintQualifying, noteFor('sprintQualifying')],
        ['Sprint', race.sprint, noteFor('sprint')],
        ['Qualifying', race.qualifying, noteFor('qualifying')],
        ['Race', race.race, noteFor('race')]
      ]
      : [
        ['FP1', race.fp1, noteFor('fp1')],
        ['FP2', race.fp2, noteFor('fp2')],
        ['FP3', race.fp3, noteFor('fp3')],
        ['Qualifying', race.qualifying, noteFor('qualifying')],
        ['Race', race.race, noteFor('race')]
      ];

    timelinePanel.innerHTML = '<div class="timeline-header"><div><strong>' + race.name + '</strong><span>' + race.location + '</span></div>' + sprintTag + '</div>' +
      sessions.map(function(session) {
        return formatSessionLine(session[0], session[1], session[2]);
      }).join('');
  }

  function getDefaultTimelineRound(currentTime) {
    // 1) Prefer current race week (window opens 4 days before FP1 and closes 3h after race start)
    for (const race of raceRows) {
      if (race.cancelled) continue;
      const fp1 = new Date(race.fp1);
      const raceStart = new Date(race.race);
      const raceEnd = new Date(raceStart.getTime() + 3 * 3600000);
      const windowStart = new Date(fp1);
      windowStart.setDate(windowStart.getDate() - 4);
      windowStart.setHours(0, 0, 0, 0);
      if (currentTime >= windowStart && currentTime <= raceEnd && !race.results) {
        return race.round;
      }
    }

    // 2) Otherwise pick next upcoming race
    const nextUpcoming = raceRows.find(function(race) {
      if (race.cancelled || race.results) return false;
      return new Date(race.race) > currentTime;
    });
    if (nextUpcoming) return nextUpcoming.round;

    // 3) Fallback to first race in dataset
    return raceRows[0] && raceRows[0].round;
  }

  const params = new URLSearchParams(window.location.search);
  const dateParam = params.get('date');
  const now = dateParam && /^\d{8}$/.test(dateParam)
    ? new Date(dateParam.slice(0,4) + '-' + dateParam.slice(4,6) + '-' + dateParam.slice(6,8) + 'T12:00:00')
    : new Date();

  renderSchedule();
  renderTimelineOptions();
  if (timelineTimezoneCode) {
    timelineTimezoneCode.textContent = getUserTimeZoneCode();
  }
  const defaultTimelineRound = getDefaultTimelineRound(now);
  if (timelineRaceSelect && defaultTimelineRound) {
    timelineRaceSelect.value = String(defaultTimelineRound);
  }
  renderTimeline(defaultTimelineRound);

  for (const r of raceRows) {
    const fp1 = new Date(r.fp1);
    const race = new Date(r.race);
    const raceEnd = new Date(race.getTime() + 3 * 3600000);

    // Show banner from 4 days before FP1 through end of race
    const windowStart = new Date(fp1);
    windowStart.setDate(windowStart.getDate() - 4);
    windowStart.setHours(0, 0, 0, 0);

    if (now >= windowStart && now <= raceEnd && !r.results && !r.cancelled) {
      const banner = document.getElementById('raceWeekBanner');

      // Derive the visitor's local calendar dates from the UTC session times
      const startDay = new Date(fp1.getFullYear(), fp1.getMonth(), fp1.getDate());
      const endDay = new Date(race.getFullYear(), race.getMonth(), race.getDate());

      let dateStr;
      if (startDay.getMonth() === endDay.getMonth()) {
        dateStr = startDay.toLocaleDateString('en-US', { month: 'long', day: 'numeric' }) + '–' + endDay.getDate();
      } else {
        dateStr = startDay.toLocaleDateString('en-US', { month: 'long', day: 'numeric' }) + ' – ' + endDay.toLocaleDateString('en-US', { month: 'long', day: 'numeric' });
      }

      // Detect visitor's timezone abbreviation (e.g. "EST", "CDT", "PST")
      const tzAbbr = Intl.DateTimeFormat('en-US', { timeZoneName: 'short' })
        .formatToParts(now).find(function(p) { return p.type === 'timeZoneName'; })?.value || '';

      document.getElementById('raceWeekName').textContent = r.name;
      document.getElementById('raceWeekMeta').innerHTML =
        'Round ' + r.round + ' \u00B7 ' + r.location + ' \u00B7 ' + dateStr +
        ' <span class="race-week-banner__tz">' + tzAbbr + '</span>';

      banner.classList.add('active');

      // Highlight matching race in the calendar grid
      var calItem = document.querySelector('.schedule-item[data-round="' + r.round + '"]');
      if (calItem) calItem.classList.add('schedule-item--active');

      break;
    }
  }

  // Mark cancelled races
  for (const r of raceRows) {
    if (r.cancelled) {
      var calItem = document.querySelector('.schedule-item[data-round="' + r.round + '"]');
      if (calItem) {
        calItem.classList.add('schedule-item--cancelled');
        var roundEl = calItem.querySelector('.schedule-item__round');
        if (roundEl) roundEl.textContent = '✗';
      }
    }
  }

  // Mark completed races
  for (const r of raceRows) {
    if (r.cancelled) continue;
    const race = new Date(r.race);
    const raceEnd = new Date(race.getTime() + 3 * 3600000);

    if (now > raceEnd || r.results) {
      var calItem = document.querySelector('.schedule-item[data-round="' + r.round + '"]');
      if (calItem && !calItem.classList.contains('schedule-item--active')) {
        calItem.classList.add('schedule-item--completed');
        var roundEl = calItem.querySelector('.schedule-item__round');
        if (roundEl) roundEl.textContent = '✓';

        if (r.results) {
          var podium = document.createElement('span');
          podium.className = 'schedule-item__podium';
          podium.innerHTML =
            '<span class="podium__p1">1 ' + r.results[0] + '</span>' +
            '<span class="podium__p2">2 ' + r.results[1] + '</span>' +
            '<span class="podium__p3">3 ' + r.results[2] + '</span>';
          calItem.querySelector('.schedule-item__info').appendChild(podium);
        }
      }
    }
  }
  if (timelineRaceSelect) {
    timelineRaceSelect.addEventListener('change', function() {
      renderTimeline(timelineRaceSelect.value);
    });
  }
  if (calendarLastUpdated) {
    calendarLastUpdated.textContent = now.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
  }
})();

// ── Championship Standings Rendering ──
(function() {
  if (!driverStandings.length && !constructorStandings.length) return;

  function posClass(pos) {
    if (pos === 1) return 'pos-1';
    if (pos === 2) return 'pos-2';
    if (pos === 3) return 'pos-3';
    return '';
  }

  function updatedLabel() {
    if (!standingsLastUpdated) return '';
    var d = new Date(standingsLastUpdated);
    return '<div class="standings-updated">Updated ' + d.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }) + '</div>';
  }

  function wikipediaIcon() {
    return '<svg class="wikipedia-mark" viewBox="0 0 128 128" fill="currentColor" aria-hidden="true"><path d="M120.85 29.21c0 .41-.13.78-.38 1.12-.26.33-.53.5-.84.5-2.49.24-4.54 1.04-6.12 2.41-1.59 1.36-3.22 3.97-4.91 7.81L82.8 99.19c-.17.54-.64.81-1.42.81-.61 0-1.08-.27-1.42-.81L65.49 68.93 48.85 99.19c-.34.54-.81.81-1.42.81-.74 0-1.23-.27-1.47-.81L20.61 41.05c-1.58-3.61-3.25-6.13-5.01-7.56-1.75-1.43-4.2-2.32-7.33-2.66-.27 0-.53-.14-.76-.43-.24-.28-.36-.61-.36-.98 0-.95.27-1.42.81-1.42 2.26 0 4.62.1 7.09.3 2.29.21 4.45.31 6.47.31 2.06 0 4.49-.1 7.29-.31 2.93-.2 5.53-.3 7.79-.3.54 0 .81.47.81 1.42 0 .94-.17 1.41-.5 1.41-2.26.17-4.04.75-5.34 1.72-1.3.98-1.95 2.26-1.95 3.85 0 .81.27 1.82.81 3.03l20.95 47.31 11.89-22.46-11.08-23.23c-1.99-4.14-3.63-6.82-4.91-8.02-1.28-1.19-3.22-1.93-5.82-2.2-.24 0-.46-.14-.68-.43-.22-.28-.33-.61-.33-.98 0-.95.23-1.42.71-1.42 2.26 0 4.33.1 6.22.3 1.82.21 3.76.31 5.82.31 2.02 0 4.16-.1 6.42-.31 2.33-.2 4.62-.3 6.88-.3.54 0 .81.47.81 1.42 0 .94-.16 1.41-.5 1.41-4.52.31-6.78 1.59-6.78 3.85 0 1.01.52 2.58 1.57 4.7l7.33 14.88 7.29-13.61c1.01-1.92 1.52-3.54 1.52-4.86 0-3.1-2.26-4.75-6.78-4.96-.41 0-.61-.47-.61-1.41 0-.34.1-.66.3-.96.21-.31.41-.46.61-.46 1.62 0 3.61.1 5.97.3 2.26.21 4.12.31 5.57.31 1.04 0 2.58-.09 4.6-.26 2.56-.23 4.71-.35 6.43-.35.4 0 .6.4.6 1.21 0 1.08-.37 1.62-1.11 1.62-2.63.27-4.75 1-6.35 2.18-1.6 1.18-3.6 3.86-5.99 8.04l-9.72 17.97 13.16 26.81 19.43-45.18c.67-1.65 1.01-3.17 1.01-4.55 0-3.31-2.26-5.06-6.78-5.27-.41 0-.61-.47-.61-1.41 0-.95.3-1.42.91-1.42 1.65 0 3.61.1 5.87.3 2.09.21 3.85.31 5.26.31 1.49 0 3.21-.1 5.16-.31 2.03-.2 3.85-.3 5.47-.3.47 0 .71.4.71 1.21Z"/></svg>';
  }

  function addWikipediaLink(social, url) {
    if (!social || !url || social.querySelector('a[aria-label="Wikipedia"]')) return;
    var link = document.createElement('a');
    link.href = url;
    link.target = '_blank';
    link.rel = 'noopener';
    link.setAttribute('aria-label', 'Wikipedia');
    link.innerHTML = wikipediaIcon();
    social.appendChild(link);
  }

  function constructorMatches(cardName, standingName) {
    if (cardName === standingName) return true;
    var aliases = {
      'Mercedes': 'Mercedes-AMG',
      'Ferrari': 'Scuderia Ferrari',
      'Cadillac': 'Cadillac F1 Team'
    };
    return aliases[cardName] === standingName || aliases[standingName] === cardName;
  }

  // Driver standings table
  if (driverStandings.length) {
    var dEl = document.getElementById('driverStandingsTable');
    if (dEl) {
      var html = '<h3>2026 Driver Standings</h3>' + updatedLabel();
      html += '<table class="standings-table"><thead><tr><th>Pos</th><th>Driver</th><th>Team</th><th>Pts</th><th>Wins</th></tr></thead><tbody>';
      driverStandings.forEach(function(d) {
        html += '<tr class="' + posClass(d.pos) + '"><td>' + d.pos + '</td><td>' + d.name + '</td><td>' + d.team + '</td><td>' + d.points + '</td><td>' + d.wins + '</td></tr>';
      });
      html += '</tbody></table>';
      dEl.innerHTML = html;
    }
  }

  // Constructor standings table
  if (constructorStandings.length) {
    var cEl = document.getElementById('constructorStandingsTable');
    if (cEl) {
      var html = '<h3>2026 Constructor Standings</h3>';
      html += '<table class="standings-table"><thead><tr><th>Pos</th><th>Team</th><th>Pts</th><th>Wins</th></tr></thead><tbody>';
      constructorStandings.forEach(function(c) {
        html += '<tr class="' + posClass(c.pos) + '"><td>' + c.pos + '</td><td>' + c.name + '</td><td>' + c.points + '</td><td>' + c.wins + '</td></tr>';
      });
      html += '</tbody></table>';
      cEl.innerHTML = html;
    }
  }

  // Inject points into driver cards
  if (driverStandings.length) {
    document.querySelectorAll('.driver-card__name').forEach(function(nameEl) {
      var name = nameEl.textContent.trim();
      var lastName = name.split(' ').slice(-1)[0];
      var match = driverStandings.find(function(d) { return d.name === name; })
        || driverStandings.find(function(d) { return d.name.split(' ').slice(-1)[0] === lastName && d.name[0] === name[0]; });
      if (match) {
        var ptsEl = document.createElement('div');
        ptsEl.className = 'driver-card__points';
        ptsEl.textContent = match.points + ' pts';
        var info = nameEl.closest('.driver-card__info');
        var social = info.querySelector('.social-links');
        if (social) info.insertBefore(ptsEl, social);
        else info.appendChild(ptsEl);
        addWikipediaLink(social, driverWikipediaLinks[match.code]);
      }
    });
  }

  // Inject points into team cards
  if (constructorStandings.length) {
    document.querySelectorAll('.team-card__name').forEach(function(nameEl) {
      var name = nameEl.textContent.trim();
      var match = constructorStandings.find(function(c) { return constructorMatches(name, c.name); });
      if (match) {
        var ptsEl = document.createElement('div');
        ptsEl.className = 'team-card__points';
        ptsEl.textContent = 'P' + match.pos + ' \u2014 ' + match.points + ' pts';
        var info = nameEl.closest('.team-card__info');
        var social = info.querySelector('.social-links');
        if (social) info.insertBefore(ptsEl, social);
        else info.appendChild(ptsEl);
        addWikipediaLink(social, constructorWikipediaLinks[match.name]);
      }
    });
  }
})();

// ── Delight: Stat card value count-up on reveal ──
(function() {
  var statValues = document.querySelectorAll('.stat-card__value');
  if (!statValues.length) return;
  if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;

  var countObserver = new IntersectionObserver(function(entries) {
    entries.forEach(function(entry) {
      if (!entry.isIntersecting) return;
      countObserver.unobserve(entry.target);
      var el = entry.target;
      // Skip values with child elements (e.g. unit toggle spans) to avoid destroying their HTML
      if (el.querySelector('.unit')) return;
      var text = el.textContent.trim();
      // Extract leading number for count-up (e.g. "1.80s" → 1.80, "$15M" → 15, "6G" → 6)
      var match = text.match(/^([^0-9]*)([0-9][0-9,]*\.?[0-9]*)(.*)$/);
      if (!match) return;
      var prefix = match[1];
      var numStr = match[2].replace(/,/g, '');
      var suffix = match[3];
      var target = parseFloat(numStr);
      if (isNaN(target) || target === 0) return;
      var hasComma = match[2].indexOf(',') > -1;
      var decimals = numStr.indexOf('.') > -1 ? numStr.split('.')[1].length : 0;
      var duration = 800;
      var start = performance.now();
      el.textContent = prefix + '0' + suffix;

      function update(now) {
        var elapsed = now - start;
        var progress = Math.min(elapsed / duration, 1);
        var eased = 1 - Math.pow(1 - progress, 3);
        var current = eased * target;
        var formatted = current.toFixed(decimals);
        if (hasComma) formatted = Number(formatted).toLocaleString('en-US', { minimumFractionDigits: decimals, maximumFractionDigits: decimals });
        el.textContent = prefix + formatted + suffix;
        if (progress < 1) requestAnimationFrame(update);
        else el.textContent = text; // restore exact original
      }
      requestAnimationFrame(update);
    });
  }, { threshold: 0.5 });

  statValues.forEach(function(el) { countObserver.observe(el); });
})();

// ── Delight: Pitstop timer click-to-replay ──
(function() {
  var timer = document.getElementById('pitstopTimer');
  if (!timer) return;
  timer.addEventListener('click', function() {
    animatePitstop();
  });
})();

// ── Delight: Console easter egg ──
console.log(
  '%c\ud83c\udfc1 Welcome to Formula 1 %c\n' +
  'Like what you see? This guide is open source.\n' +
  'Contribute: https://github.com/joshferrara/welcome-to-f1\n',
  'font-size: 20px; font-weight: bold; color: #E10600; padding: 8px 0;',
  'font-size: 13px; color: #888;'
);
